### PR TITLE
remove quote that was appended to error messages from jsonlint

### PR DESCRIPTION
**Pull request by gustavnikolaj**
I got:

```
Error: Parse error on line 2:
{    "foo": "bar}
------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'"
File: "/home/gustav/Projects/node-cjson/test/fixtures/invalid.cjson"
```

Notice the extra quote at the end of the Expecting line.

Unfortunately there was not much coverage of the expected error messages, so I was not able to see if the quote was there for a reason - I looked manually but did not find it. I'm sorry if I missed something.

### CODE REVIEW

**Comment by kof** [comment]
thanks

**Comment by gustavnikolaj** [comment]
Thanks for taking the PR :-) When will you have time to release a new package to npm? :-)

**Comment by kof** [comment]
done

**Comment by gustavnikolaj** [comment]
thanks!

**Pull request merged**
